logger:
  level: -100
  add_source: true
  handler_type: text

postgres:
  conn_string: "
    user=${POSTGRES_USER}
    password=${POSTGRES_PASSWORD}
    dbname=${POSTGRES_DB}
    host=localhost
    port=5432
  "

http_server:
  address: localhost
  port: 8080
  endpoints_v1:
    cors:
      allow_origins: "*"
      allow_methods: "GET, POST, PUT PATCH, DELETE"
      allow_headers: "application/json"


